/**
 * Component type definitions — the single source of truth for all
 * visual, behavioral, and configuration properties.
 */
export const TYPES = {
  client: {
    id: 'client', name: 'Client', icon: '🖥️', color: '#58a6ff', bg: '#102040',
    category: 'Traffic', w: 96, h: 68,
    desc: 'End users or external services sending requests into your system.',
    behavior: 'SOURCE — generates request packets. Configurable read/write mix.',
    baseLatencyMs: 0,
    defaultMaxRPS: Infinity,
    isSource: true, maxIn: 0, maxOut: Infinity,
    defaultConfig: { rps: 5, trafficPattern: 'steady', readWriteRatio: 0.8 },
    configFields: [
      { key: 'rps', label: 'Requests / sec', type: 'number', min: 1, max: 200, step: 1 },
      { key: 'readWriteRatio', label: 'Read / Write Mix', type: 'range', min: 0, max: 1, step: 0.05 },
      { key: 'trafficPattern', label: 'Traffic Pattern', type: 'select',
        options: [{ v: 'steady', l: 'Steady' }, { v: 'spike', l: 'Bursty Spikes' }] },
    ],
  },
  load_balancer: {
    id: 'load_balancer', name: 'Load Balancer', icon: '⚖️', color: '#79c0ff', bg: '#0e2840',
    category: 'Traffic', w: 118, h: 68,
    desc: 'Distributes incoming requests evenly across a pool of servers.',
    behavior: 'Round-robin: routes each packet to the next downstream server in order.',
    baseLatencyMs: 1, defaultMaxRPS: 100000,
    maxIn: Infinity, maxOut: Infinity,
    defaultConfig: { maxRPS: 100000 },
    configFields: [{ key: 'maxRPS', label: 'Max RPS', type: 'number', min: 1, max: 500000, step: 100 }],
  },
  api_gateway: {
    id: 'api_gateway', name: 'API Gateway', icon: '🔗', color: '#ffa657', bg: '#2a1800',
    category: 'Traffic', w: 110, h: 68,
    desc: 'Central entry point. Handles auth, rate-limiting, and routing.',
    behavior: 'Routes requests to downstream services. Enforces rate limits.',
    baseLatencyMs: 3, defaultMaxRPS: 50000,
    maxIn: Infinity, maxOut: Infinity,
    defaultConfig: { maxRPS: 50000 },
    configFields: [{ key: 'maxRPS', label: 'Max RPS', type: 'number', min: 1, max: 200000, step: 100 }],
  },
  cdn: {
    id: 'cdn', name: 'CDN', icon: '🌍', color: '#d2a8ff', bg: '#1e1040',
    category: 'Traffic', w: 88, h: 68,
    desc: 'Content Delivery Network. Serves cached static content from edge nodes.',
    behavior: 'Configurable hit rate. Hits serve instantly; misses forward to origin.',
    baseLatencyMs: 2, defaultMaxRPS: 500000,
    maxIn: Infinity, maxOut: Infinity,
    defaultConfig: { hitRate: 0.85, maxRPS: 500000 },
    configFields: [
      { key: 'hitRate', label: 'Cache Hit Rate', type: 'range', min: 0, max: 1, step: 0.05 },
    ],
  },
  web_server: {
    id: 'web_server', name: 'Web Server', icon: '🌐', color: '#3fb950', bg: '#0e2a14',
    category: 'Compute', w: 106, h: 68,
    desc: 'Handles HTTP requests, serves pages, coordinates with backends.',
    behavior: 'Processes requests and forwards data queries downstream.',
    baseLatencyMs: 10, defaultMaxRPS: 1000,
    maxIn: Infinity, maxOut: Infinity,
    defaultConfig: { maxRPS: 1000 },
    configFields: [{ key: 'maxRPS', label: 'Max RPS', type: 'number', min: 1, max: 100000, step: 1 }],
  },
  app_server: {
    id: 'app_server', name: 'App Server', icon: '⚙️', color: '#56d364', bg: '#0e2a14',
    category: 'Compute', w: 106, h: 68,
    desc: 'Runs application business logic. Stateless — scale horizontally.',
    behavior: 'Processes business logic and forwards to the data layer.',
    baseLatencyMs: 20, defaultMaxRPS: 500,
    maxIn: Infinity, maxOut: Infinity,
    defaultConfig: { maxRPS: 500 },
    configFields: [{ key: 'maxRPS', label: 'Max RPS', type: 'number', min: 1, max: 100000, step: 1 }],
  },
  cache: {
    id: 'cache', name: 'Cache', icon: '⚡', color: '#f0883e', bg: '#2a1500',
    category: 'Data', w: 92, h: 68,
    desc: 'In-memory store (Redis/Memcached). Sub-millisecond reads.',
    behavior: 'READ packets: hit/miss check. WRITE packets: bypass cache, go straight to DB.',
    baseLatencyMs: 1, defaultMaxRPS: 100000,
    maxIn: Infinity, maxOut: Infinity,
    defaultConfig: { hitRate: 0.80, maxRPS: 100000 },
    configFields: [
      { key: 'hitRate', label: 'Cache Hit Rate', type: 'range', min: 0, max: 0.99, step: 0.05 },
      { key: 'maxRPS', label: 'Max RPS', type: 'number', min: 1, max: 1000000, step: 100 },
    ],
  },
  sql_db: {
    id: 'sql_db', name: 'SQL DB', icon: '🗃️', color: '#f78166', bg: '#2a0e0e',
    category: 'Data', w: 96, h: 68,
    desc: 'Relational DB (Postgres, MySQL). ACID transactions, strong consistency.',
    behavior: 'SINK — accepts both reads and writes. Higher write latency (WAL + fsync).',
    baseLatencyMs: 20, defaultMaxRPS: 5000,
    isSink: true, maxIn: Infinity, maxOut: 0,
    defaultConfig: { maxRPS: 5000 },
    configFields: [{ key: 'maxRPS', label: 'Max RPS', type: 'number', min: 1, max: 100000, step: 10 }],
  },
  nosql_db: {
    id: 'nosql_db', name: 'NoSQL DB', icon: '📊', color: '#ff9492', bg: '#2a0e0e',
    category: 'Data', w: 104, h: 68,
    desc: 'Document/key-value store (MongoDB, DynamoDB). Horizontal scale.',
    behavior: 'SINK — high write throughput, eventual consistency.',
    baseLatencyMs: 5, defaultMaxRPS: 50000,
    isSink: true, maxIn: Infinity, maxOut: 0,
    defaultConfig: { maxRPS: 50000 },
    configFields: [{ key: 'maxRPS', label: 'Max RPS', type: 'number', min: 1, max: 500000, step: 10 }],
  },
  message_queue: {
    id: 'message_queue', name: 'Msg Queue', icon: '📨', color: '#e3b341', bg: '#251a00',
    category: 'Messaging', w: 104, h: 72,
    desc: 'Async broker (Kafka, RabbitMQ). Decouples producers from consumers.',
    behavior: 'Buffers packets; delivers async. Queue fills if consumers too slow.',
    baseLatencyMs: 5, defaultMaxRPS: 1000000,
    maxIn: Infinity, maxOut: Infinity,
    defaultConfig: { maxRPS: 1000000, deliveryDelayMs: 800, maxDepth: 10000 },
    configFields: [
      { key: 'deliveryDelayMs', label: 'Delivery Delay (ms)', type: 'number', min: 100, max: 5000, step: 100 },
      { key: 'maxDepth', label: 'Max Queue Depth', type: 'number', min: 100, max: 1000000, step: 100 },
    ],
  },
  worker: {
    id: 'worker', name: 'Worker', icon: '👷', color: '#bc8cff', bg: '#1a0e30',
    category: 'Messaging', w: 96, h: 68,
    desc: 'Background job processor. Consumes from a queue, does heavy work async.',
    behavior: 'Processes tasks slowly but reliably. Low throughput, no user-facing SLA.',
    baseLatencyMs: 150, defaultMaxRPS: 100,
    maxIn: Infinity, maxOut: Infinity,
    defaultConfig: { maxRPS: 100 },
    configFields: [{ key: 'maxRPS', label: 'Max RPS', type: 'number', min: 1, max: 1000, step: 1 }],
  },
};

export const PALETTE_GROUPS = [
  { label: 'Traffic',   types: ['client', 'load_balancer', 'api_gateway', 'cdn'] },
  { label: 'Compute',   types: ['web_server', 'app_server', 'worker'] },
  { label: 'Data',      types: ['cache', 'sql_db', 'nosql_db'] },
  { label: 'Messaging', types: ['message_queue'] },
];
